# --- !Ups

create table ANIMALS (
  ID integer generated by default as identity(start with 1) not null primary key,
  NAME varchar not null,
  POSITION integer not null);

create unique index POSITION_INDEX on ANIMALS (POSITION);

insert into ANIMALS (NAME, POSITION) values ('Alligator', 1);
insert into ANIMALS (NAME, POSITION) values ('Bear', 2);
insert into ANIMALS (NAME, POSITION) values ('Cat', 3);
insert into ANIMALS (NAME, POSITION) values ('Dog', 4);
insert into ANIMALS (NAME, POSITION) values ('Elephant', 5);
insert into ANIMALS (NAME, POSITION) values ('Fish', 6);
insert into ANIMALS (NAME, POSITION) values ('Goat', 7);
insert into ANIMALS (NAME, POSITION) values ('Horse', 8);
insert into ANIMALS (NAME, POSITION) values ('Iguana', 9);
insert into ANIMALS (NAME, POSITION) values ('Jackal', 10);
insert into ANIMALS (NAME, POSITION) values ('Kangaroo', 11);
insert into ANIMALS (NAME, POSITION) values ('Lion', 12);
insert into ANIMALS (NAME, POSITION) values ('Mouse', 13);
insert into ANIMALS (NAME, POSITION) values ('Narwhal', 14);
insert into ANIMALS (NAME, POSITION) values ('Otter', 15);
insert into ANIMALS (NAME, POSITION) values ('Pig', 16);
insert into ANIMALS (NAME, POSITION) values ('Quail', 17);
insert into ANIMALS (NAME, POSITION) values ('Rabbit', 18);
insert into ANIMALS (NAME, POSITION) values ('Sheep', 19);
insert into ANIMALS (NAME, POSITION) values ('Tiger', 20);
insert into ANIMALS (NAME, POSITION) values ('Uakari', 21);
insert into ANIMALS (NAME, POSITION) values ('Vulture', 22);
insert into ANIMALS (NAME, POSITION) values ('Wolf', 23);
insert into ANIMALS (NAME, POSITION) values ('X-ray tetra', 24);
insert into ANIMALS (NAME, POSITION) values ('Yak', 25);
insert into ANIMALS (NAME, POSITION) values ('Zebra', 26);

# --- !Downs

drop table ANIMALS;
